server:
  port: 1212
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    web-application-type: servlet
logging:
  level:
    org.springframework.security: DEBUG
